quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${HEVYFIT_DB_USER}
quarkus.datasource.password=${HEVYFIT_DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hevyfit_routines

quarkus.hibernate-orm.schema-management.strategy=update
